### ISSUE TITLE
benchmarks...

### ISSUE THREAD

**Issue by kylebakerio** [davidmarkclements/rfdc#13]
Would really like to have something to compare these benchmarks to. Could you put up a jsperf link comparing this to a few alternatives? Not sure what to do with the benchmarks you've listed yourself.

**Comment by Quelklef** [comment]
https://jsbench.me/1wkbcjh2py

**Comment by BridgeAR** [comment]
@Quelklef thanks for the additional benchmark!

@kylebakerio I hope that helps? I also just added another library to the comparison in the README. I hope that helps.
