### ISSUE TITLE
Support for Map and Set types

### ISSUE THREAD

**Issue by derekparsons718** [davidmarkclements/rfdc#17]
I would love to see support added for the native [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) and [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) types.

They are becoming increasingly popular and I use them all the time. But the current behavior when cloning them is to return an empty object:

```javascript
const data = {
    set: new Set([1, 2, 3]),
    map: new Map([
        ["a", 1],
        ["b", 2],
        ["c", 3]
    ])
};
console.log(data); // {set: {1, 2, 3}, map: {"a" => 1, "b" => 2, "c" => 3}}
console.log(clone(data)); // {set: {}, map: {}}
```

**Comment by davidmarkclements** [comment]
PR's for this are more than welcome!
