### ISSUE TITLE
Add `structuredClone` to benchmarks

### ISSUE THREAD

**Issue by silverwind** [davidmarkclements/rfdc#35]
https://developer.mozilla.org/en-US/docs/Web/API/structuredClone

In my limited testing, it's around 2-3 times slower than this module with `proto: false, circles: true` options.

**Comment by mcollina** [comment]
would you like to send a PR? Adding that it would be awesome.

**Comment by silverwind** [comment]
Could have a look I guess. It will require Node.js 17 or higher.

**Comment by mcollina** [comment]
For benchmarks it's ok

**Comment by rluvaton** [comment]
I see @mcollina added it in 60507bfc0af798f033f645cebdf4aabb97a3ab77 but did not update the readme with the results

**Comment by mcollina** [comment]
Done
