### ISSUE TITLE
The 1.3.1 version is not released on NPM

### ISSUE THREAD

**Issue by Vitalii4as** [davidmarkclements/rfdc#36]
The last current version on npm website is 1.3.0, but I see a commit with changing version to 1.3.1. Shouldn't it be released?
https://www.npmjs.com/package/rfdc?activeTab=versions
![image](https://github.com/davidmarkclements/rfdc/assets/71256742/2d169ff2-09cb-49d7-81c5-fca29d06e711)

**Comment by mcollina** [comment]
done
