### ISSUE TITLE
UMD wrapper to able use rfdc in browsers

### ISSUE THREAD

**Issue by STUkh** [davidmarkclements/rfdc#5]
Good approach, but only one modular system support unable to use this plugin in different envs, UMD wrapper will be good approach to make rfdc consistent.

**Comment by davidmarkclements** [comment]
this is already compatible with browserify, webpack, babel... so its fully interoperable with any envs that have a bundling step

if you're in the amazing position where bundling isn't necessary, you can get rfdc as a global using bundle.run:

```html
<script src=https://bundle.run/rfdc@1.1.4></script>
```

If you're referring to ES6 modules, UMD doesn't support them
